export type IconName =
  | "menu"
  | "close"
  | "arrow"
  | "check"
  | "message"
  | "whatsapp"
  | "mail"
  | "tiktok"
  | "code"
  | "layers"
  | "rocket"
  | "globe"
  | "store"
  | "heart"
  | "dumbbell"
  | "building"
  | "briefcase"
  | "shopping"
  | "spark";
export type IconProps = { name: IconName; size?: number; className?: string; title?: string };
